# Generated by Django 2.0.7 on 2018-07-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miltonpainting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paintestimateuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='paintestimateuser',
            name='contractor_cost',
        ),
        migrations.AlterField(
            model_name='paintestimate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paintestimateuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
