# Generated by Django 2.0.7 on 2018-07-29 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miltonpainting', '0002_auto_20180728_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintestimate',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.date(2018, 7, 29), help_text='Date and time for your in person estimate'),
        ),
    ]
