# Generated by Django 2.0.7 on 2018-07-29 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('miltonpainting', '0003_paintestimate_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintestimate',
            name='date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Date and time for your in person estimate'),
        ),
    ]
