# Generated by Django 2.0.7 on 2018-07-29 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('miltonpainting', '0005_auto_20180729_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintestimateuser',
            name='date_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
