# Generated by Django 2.0.7 on 2018-07-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miltonpainting', '0006_auto_20180729_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paintestimateuser',
            name='user_name',
        ),
        migrations.AddField(
            model_name='paintestimateuser',
            name='city',
            field=models.CharField(default='Toronto', max_length=200),
        ),
        migrations.AlterField(
            model_name='paintestimateuser',
            name='date_time',
            field=models.DateField(),
        ),
    ]
