# Generated by Django 2.0.7 on 2018-07-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miltonpainting', '0008_auto_20180730_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintestimateuser',
            name='date_time',
            field=models.DateField(),
        ),
    ]
