# Generated by Django 2.0.7 on 2018-07-30 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miltonpainting', '0009_auto_20180730_0755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paintestimateuser',
            old_name='date_time',
            new_name='estimate_date',
        ),
    ]
